### ISSUE TITLE
no way to download a vClusters Kubeconfig using the terraform provider.

### ISSUE THREAD

**Issue by gumpumadhu** [loft-sh/terraform-provider-loft#144]
no way to download a vClusters Kubeconfig using the terraform provider.

**Comment by deniseschannon** [comment]
This is a late response, but this repository is no longer maintained. 

In our latest versions of vcluster, there are ways to set up your vcluster.yaml to export the kube config as well. 

https://www.vcluster.com/docs/vcluster/configure/vcluster-yaml/export-kube-config
